### ISSUE TITLE
ipmitool path on FreeBSD is different (or custom ipmitool binary path)

### ISSUE THREAD

**Issue by olevole** [horsefish/bmc#26]
Hi.

This module works perfectly on a FreeBSD platform with ipmitool (*thanks!*) except for one problem: on FreeBSD all 3rd party software installed with a `/usr/local/` prefix, e.g. full/realpath for ipmitool is `/usr/local/bin/ipmitool', instead of '/usr/bin/ipmitool'

Сan you add a separate case for FreeBSD where we could set alternative path, e.g. something like:
```
diff --git a/lib/puppet_x/ipmi/ipmitool.rb b/lib/puppet_x/ipmi/ipmitool.rb
index aeed852..75cb6fa 100644
--- a/lib/puppet_x/ipmi/ipmitool.rb
+++ b/lib/puppet_x/ipmi/ipmitool.rb
@@ -9,7 +9,12 @@ class Ipmitool
   end
 
   def self.ipmi_call(ipmi_args, cmd_args, suppress_error = false)
-    cmd = ['/usr/bin/ipmitool']
+    case facts[:kernel]
+    when 'freebsd'
+      cmd = ['/usr/local/bin/ipmitool']
+    else
+      cmd = ['/usr/bin/ipmitool']
+    end
     unless ipmi_args[:bmc_server_host].nil? ||
            ipmi_args[:bmc_username].nil? ||
            ipmi_args[:bmc_password].nil?
```

^^ unfortunately, I don’t know how to access the puppet facts from *lib/puppet_x/ipmi/ipmitool.rb*, so this example is non-working.

In addition, it would be nice to be able to override binary paths, for example:
```
bmc::oem::ipmi::ipmitool_path: /usr/bin/ipmitool
```
and use 'data/os/<family>/' hier for flexible per-platform/distro params.

**Comment by olevole** [comment]
@ltning did you observe this problem when adding support for FreeBSD via https://github.com/horsefish/bmc/issues/22 ?

**Comment by myMarck** [comment]
I agree a better long term solution would be to move the tool path to Hiera and have created #28

**Comment by olevole** [comment]
@myMarck Thanks!
